# Generated by Django 6.0.1 on 2026-01-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='copies_avilable',
            new_name='copies_available',
        ),
    ]
