# Generated by Django 6.0.1 on 2026-06-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_genre_remove_book_genre_book_genres'),
    ]

    operations = [
    ]
